clear
% Average RMSE, sqrt(e(R)) and runtime over 10 runs of run_table 8.1.

nrun = 10;
noiselevel = [0 1e-10 1e-8 1e-6 1e-4];

E = 0;
RMSE = 0;
T = 0;

for k = 1:nrun
    fprintf('run_table1: %d / %d\n', k, nrun);
    [mj1, mj2, mj3] = run_table1();
    E = E + mj1;
    RMSE = RMSE + mj2;
    T = T + mj3;
end

E = E / nrun;
RMSE = RMSE / nrun;
T = T / nrun;

write_table1_10_tex(noiselevel, RMSE, E, T);

function write_table1_10_tex(noiselevel, RMSE, E, T)
% Table 8.1 format, averaged over 10 random tests.

fid = fopen('table1_10times.tex', 'w');
if fid < 0
    error('Could not open table1_10times.tex for writing.');
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

fprintf(fid, '%% Generated by run_table1_10times.m\n');
fprintf(fid, '\\begin{table}[h!!!]\n');
fprintf(fid, '\\caption{The average {\\tt RMSE}, $\\sqrt{e(R)}$ and runtime (s) over 10 random tests for Example \\ref{eg:Eg1}}\n');
fprintf(fid, '%%\\hskip -8mm\n');
fprintf(fid, '\\begin{center}\\resizebox{150mm}{39mm}{\\tabcolsep0.08in\n');
fprintf(fid, '\\begin{tabular}{|c|c|c|c|c|c|c|}\\hline\n');

header = ['Method &{\\sf m-d-Lawson}(10)  &{\\sf v-AAA-Lawson}(10) &  block-AAA  &  RKFIT(10)  &  Loewner & VF\\\\\n'];
types  = [' & type (5,6)  & type (5,6)  &   type (6,6)   &  type (6,6) &   type (6,6)&   type (6,6) \\\\\n'];

fprintf(fid, header);
fprintf(fid, [' {\\tt RMSE}', types]);
fprintf(fid, '\\hline\n\\hline\n');
write_rows(fid, noiselevel, RMSE);

fprintf(fid, ' \\hline\\hline\n');
fprintf(fid, header);
fprintf(fid, ['$\\sqrt{e(R)}$', types]);
fprintf(fid, '\\hline\n');
write_rows(fid, noiselevel, E);

fprintf(fid, ' \\hline\\hline\n');
fprintf(fid, header);
fprintf(fid, ['runtime (s)', types]);
fprintf(fid, '\\hline\n');
write_rows(fid, noiselevel, T);

fprintf(fid, ' \\hline\n');
fprintf(fid, '\\end{tabular}\n');
fprintf(fid, '}\n');
fprintf(fid, '\\end{center}\n');
fprintf(fid, '\\label{Tab:toy1-a}\n');
fprintf(fid, '\\end{table}\n');

fprintf('Wrote %s\n', fullfile(pwd, 'table1_10times.tex'));
end

function write_rows(fid, noiselevel, M)
for j = 1:length(noiselevel)
    if noiselevel(j) == 0
        lab = '$   \varsigma = 0 $';
    else
        lab = sprintf('$   \\varsigma = 10^{%d}  $', round(log10(noiselevel(j))));
    end
    fprintf(fid, '%s   &        %.4e  &        %.4e   &      %.4e &      %.4e &      %.4e &      %.4e  \\\\  \n', ...
        lab, M(j,1), M(j,2), M(j,3), M(j,4), M(j,5), M(j,6));
end
end
